### ISSUE TITLE
getting wrong msg when selecting shaped plaza map in bulk buy section (screenshot in comment)

### ISSUE THREAD

**Issue by eskoONE** [StefanKunde/TradeMaster_POE#19]
https://i.imgur.com/B8BCBth.jpg

i get a whisper msg for augments which seems very odd.

**Comment by veenarm** [comment]
It's because there's no max price marked per map, the setValidPricePerMap is false because it's not greater than 0 (it's set to true if its >= 1 or <= 1000.

Maybe could treat blank as ignore max currency, just filter it regardless?

**Comment by veenarm** [comment]
This should be fixed in the MR released 1.5 version.

@StefanKunde - I have a bunch of other things to discuss with this if you'd like add me in game, current name this league is PulsingMember

**Comment by StefanKunde** [comment]
@veenarm Sure. You can join my discord server and we can talk about it.
https://discord.gg/jgdc49D

**Comment by StefanKunde** [comment]
Should be fixed now by veenarm.
