### ISSUE TITLE
[Suggestion] Gem buy with quality normalizing

### ISSUE THREAD

**Issue by Crazy-KSK** [StefanKunde/TradeMaster_POE#23]
It's quite a hassle scanning though trying to find the gems with the best quality to price ratio, like when I try to buy 6 new empowers I have to look for ones with quality that are cheaper then the base gem+ quality added manually.

I hope you don't mid me posting my suggestion here.
Thanks.

**Comment by StefanKunde** [comment]
I'm already planing to add a feature for buying gems like that.
