### ISSUE TITLE
Missing fossil

### ISSUE THREAD

**Issue by kharom1** [StefanKunde/TradeMaster_POE#26]
Hi, macro is missing Pristine Fossil.

**Comment by veenarm** [comment]
@StefanKunde This should of been fixed in your merge as it was added in the above.
P.S I messaged you on reddit if you want to properly co-ord this, otherwise my current builds are api driven so these lists don't require updates to the application.

**Comment by StefanKunde** [comment]
Should be fixed now by veenarm.
