### ISSUE TITLE
Change League Option

### ISSUE THREAD

**Issue by mangjaya** [StefanKunde/TradeMaster_POE#27]
Hi i really love your program, can u make it work on Hardcore Betrayal, or adding change League Option ?

**Comment by veenarm** [comment]
I'm looking into this as well, hopefully have a PR (if the owner lets me) this weekend.

**Comment by mangjaya** [comment]
Thanks alot veenarm :)

**Comment by veenarm** [comment]
I have this ready with a few other fixes but will wait for the other MR Pull to happen before i attempt this one.

**Comment by mangjaya** [comment]
It's work 👍

**Comment by StefanKunde** [comment]
Included in the new update!
Thanks to veenarm!
