### ISSUE TITLE
Bug: Bulk buying maps message

### ISSUE THREAD

**Issue by Reaver01** [StefanKunde/TradeMaster_POE#35]
When you buy maps in bulk it doesn't put a space between the number and currency type.
Message ends up looking like this:

@name Hi, I'd like to buy your 2 Bazaar Map (T7) for my 4chaos orb in Synthesis

This makes it so trade tools won't pick up the buying currency.

**Comment by veenarm** [comment]
Will look at it tonight and hopefully have a fix.

**Comment by veenarm** [comment]
Fixed in 1.5.1 - @Name Hi, I'd like to buy your 4 Academy Map (T7) for my 4 chaos orb in Synthesis
