### ISSUE TITLE
Minimize bug 1.5

### ISSUE THREAD

**Issue by zimko** [StefanKunde/TradeMaster_POE#36]
Then minimize and reopen have this bug (same with 2 computers)

See this : https://puu.sh/D4SB1/302f63652c.png

Thank's !

**Comment by veenarm** [comment]
Hey mate, yes I did see this at one stage, but was difficult to replicate. If you have exact way to get it (because generally minimize and re-open works fine).
I have a large update coming in soon that will fix this regardless.

**Comment by StefanKunde** [comment]
Hey guys!

I could not replicate eather.
So I will close this for now.

Just reopen when you can.
