### ISSUE TITLE
Enhancement - item buy tab for other items (prophecies, incubators, div-cards, common items, etc.) through name

### ISSUE THREAD

**Issue by ciyf** [StefanKunde/TradeMaster_POE#38]
Hello Stephan, 
i love your Tool it helps me very much with buying maps and exchanging currency. 
Last night i dreamed of an enhancement where you can do the same for any item on the market. 
The idea is, to be able to put in a name and get the offers-list like in the mapbuying-tab
This would be useful for div-cards and prophecies commom items like tabula rasa where most dont respont etc.
Sadly im not expirienced enougth to do it 100% on my own therefor I am writig this Ticket.
Thank you very much for your Tool!

**Comment by ciyf** [comment]
A suggestion might be to make the combobox in the currency tab editable, so you can enter anything you want therefor enabling this enhancement if you enter any item and put in the wanted currency.

**Comment by StefanKunde** [comment]
Hey thanks for that feature request.
I like the idea and was thinking about something thats pretty similar, long ago.
When I have the time for it, I will implement it within the next release.

Happy new year!
