### ISSUE TITLE
Hello, I am very interested in how you make equipment price forecasts. Can you have an interest to talk about it?

### ISSUE THREAD

**Issue by youboyTizzyT** [StefanKunde/TradeMaster_POE#41]
I am currently researching the price forecast. The POE data source is obtained from this website https://www.pathofexile.com/api/public-stash-tabs. At present, some machine learning models are used to price. Regression prediction.
The first question, can you tell me what method you are using to predict the price of rare equipment, but also machine learning? Tell me if there are other troubles.
Second question, can you share your prediction method? I am very happy to share this knowledge with you.
Thanks.

**Comment by veenarm** [comment]
We don't do any predictions, all data is retrieved from other sources.
The program also doesn't contact public-stash-tabs at all, only poeninja.com and the /trade websites.
