### ISSUE TITLE
Won't launch

### ISSUE THREAD

**Issue by H4xoltl** [StefanKunde/TradeMaster_POE#44]
Hey, 

This app used to work in 3.7.0 and older, but now I can't launch it, even with admin priviledge.

Double clicking the app doesn't cause anything to happen. PoE is windowed, windows 10 and java are all updated

**Comment by StefanKunde** [comment]
Hey,

it was not working because I did not update it for the current league.
Its updated now and will work with metamorph league.
Just download the newest release.
