### ISSUE TITLE
Automatically get the list of active leagues instead of manually updating it

### ISSUE THREAD

**Issue by JusKillmeQik** [StefanKunde/TradeMaster_POE#47]
You can use this API to get the active leagues and populate your list. I know you're working on a bunch right now, so let me know if you'd like me to try and implement it.

https://api.poe.watch/leagues

**Comment by StefanKunde** [comment]
Hey,

yes thats the most optimal setup for sure.
Same for maps that will change over the leagues (this would self maintain the app over leagues).

If you have the time for it, go for it and send a PR :)

**Comment by JusKillmeQik** [comment]
Leaving a note for the exact APIs to use:

https://api.poe.watch/leagues
https://api.poe.watch/get?league=Metamorph&category=map

I'll need to familiarize myself with your code but I'll take a stab at it in the next two weeks

**Comment by veenarm** [comment]
I have a new version to migrate over, which has some of this already but taking it from my own python api serving literally just a json file.

I'll do a PR first so you can see.

**Comment by veenarm** [comment]
https://github.com/StefanKunde/TradeMaster_POE/pull/48
