### ISSUE TITLE
Can you make it to not check for PoE window? 

### ISSUE THREAD

**Issue by MATRASUS** [StefanKunde/TradeMaster_POE#50]
I don't think it is necessary to hide tool's window before PoE window appears. Also if you change the name of PoE window this tool will be hidden even after PoE loads.
Any option to run this tool unhidden (without PoE client opened) would help.

**Comment by StefanKunde** [comment]
Hey!

This is currently not possible.
I'm working on a new version with electron. There will be an option for a standalone client.

Check my readme to follow the dev if you like to.

**Comment by veenarm** [comment]
@MATRASUS - in v1.7.3 over in my fork I have removed the auto hide/closing if PoE is open or not, so you can force close the app at anytime..
- Note: It still expects your window to be Path of Exile for foreground when you select 'Next' with auto copy/paste.

**Comment by MATRASUS** [comment]
Thank you so much for the info, I'll check it out18.09.2020, 21:48, "John" <notifications@github.com>:
@MATRASUS - in v1.7.3 over in my fork I have removed the auto hide/closing if PoE is open or not, so you can force close the app at anytime..

Note: It still expects your window to be Path of Exile for foreground when you select 'Next' with auto copy/paste.
